[workspace]
resolver = "2"
members = [
    "app",
    "desktop",
    "mobile",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
winit = { version = "0.30.3", features = ["android-native-activity"] }
